/**
 * @file AAR.h
 * @brief Axis Aligned Rectangles - the static collision world, plus its broadphase grid.
 *
 * Portal's test chambers are built entirely out of axis aligned boxes, so the
 * static collision geometry can be reduced to a soup of flat, axis aligned
 * rectangles with an outward normal. That makes contact generation against a
 * rigid body far cheaper than a general polygon soup would be, at the cost of
 * being unable to represent anything slanted.
 *
 * @par Broadphase
 * A room can hold up to @ref NUMAARS rectangles, which is far too many to test
 * one by one against every cube every frame. @ref generateGrid therefore bins
 * them into a 2D grid over the XZ plane (height is ignored - rooms are wider
 * than they are tall). A body only ever tests against the rectangles in the
 * cells its bounding box overlaps.
 *
 * The grid's cell size is not fixed: it starts at @ref ORIGNODESIZE and keeps
 * doubling until the node array fits in the ARM7's very limited heap, so a
 * huge level degrades to a coarser grid rather than failing to allocate.
 *
 * @par Portal guide rectangles
 * Each portal owns four extra rectangles, generated by @ref generateGuidAAR,
 * forming a funnel around its mouth. They are what stops a cube from catching
 * on the wall it is passing through - the real wall rectangles are still there,
 * so without the funnel a body would collide with the surface the portal is
 * cut into.
 *
 * @see OBB.h for the rigid bodies these rectangles collide with.
 */

#ifndef AAR_H //axis aligned rectangle !
#define AAR_H

#define NUMAARSEGMENTS (4) /**< Edges of a rectangle. */

#define ORIGNODESIZE (4096)  /**< Initial broadphase cell size, in f32 units. */
#define NODESIZE (nodeSize)  /**< Current broadphase cell size; see @ref nodeSize. */

/**
 * @brief A one-sided, axis aligned collision rectangle.
 *
 * ::position is the corner with the smallest coordinates and ::size is the
 * extent from there, so the rectangle spans @c position .. @c position+size.
 * One component of ::size is zero - that is the axis ::normal points along.
 */
typedef struct
{
	vect3D position; /**< Minimum corner. */
	vect3D size;     /**< Extent from ::position; flat along one axis. */
	vect3D normal;   /**< Outward normal; bodies are only pushed out on this side. */
	bool used;       /**< False when this slot is free or the rectangle is disabled. */
}AAR_struct;
// 4*3 + 4*3 + 4*3 + 1 = 37
// 2*2 + 1 + 3*1 + 1 + 1 = 10

/**
 * @brief One cell of the broadphase grid: the rectangles overlapping it.
 */
typedef struct
{
	u16* data; /**< Array of rectangle indices, or NULL if the cell is empty. */
	u8 length; /**< Number of indices in ::data. */
}node_struct;

/**
 * @brief The broadphase grid itself - a 2D array of cells over the XZ plane.
 */
typedef struct
{
	node_struct* nodes; /**< Row-major @c width x @c height cell array. */
	u16 width, height;  /**< Grid dimensions, in cells. */
	vect3D m, M;        /**< World-space bounds the grid covers (min and max corner). */
}grid_struct;

/**
 * @brief Current broadphase cell size.
 *
 * Chosen by @ref generateGrid - it starts at @ref ORIGNODESIZE and doubles
 * until the node array fits in the available ARM7 heap.
 */
extern u32 nodeSize;

/** @brief Frees every rectangle slot and drops the broadphase grid. */
void initAARs(void);

/** @brief Debug draw hook. Compiled out. */
void drawAARs(void);

/**
 * @brief Enables or disables a rectangle.
 *
 * Flips AAR_struct::used, which is how doors and moving walls stop colliding
 * when they open. Note that the broadphase grid is *not* rebuilt: the index
 * stays in its cells and is simply skipped.
 *
 * @param id rectangle index.
 */
void toggleAAR(u16 id);

/**
 * @brief Rebuilds the broadphase grid over all live rectangles.
 *
 * Must be called after a batch of @ref createAAR calls, which is exactly what
 * the @ref PI_MAKEGRID command is for.
 *
 * @param g grid to fill, or NULL to rebuild the engine's own grid.
 */
void generateGrid(grid_struct* g);

/**
 * @brief Moves a rectangle without rebuilding the grid.
 *
 * Only safe for small movements that keep the rectangle inside the same cells.
 *
 * @param id       rectangle index.
 * @param position new minimum corner.
 */
void updateAAR(u16 id, vect3D position);

/**
 * @brief Generates every static contact for one rigid body.
 *
 * Looks up the grid cells the body overlaps, tests the rectangles found there
 * (skipping duplicates, since one rectangle can span several cells), then adds
 * the portal guide rectangles and the moving platforms. Also records which
 * upward-facing rectangle the body is resting on in OBB_struct::groundID.
 *
 * @param o     body to gather contacts for.
 * @param sleep true when the body is asleep, in which case the static world is
 *              skipped entirely and only platforms are tested.
 */
void AARsOBBContacts(OBB_struct* o, bool sleep);

/**
 * @brief Fills a rectangle slot.
 * @param id       slot index, must be below @ref NUMAARS.
 * @param position minimum corner.
 * @param size     extent; flat along the normal's axis.
 * @param normal   outward normal.
 * @return the rectangle that was created, or NULL if @p id is out of range.
 */
AAR_struct* createAAR(u16 id, vect3D position, vect3D size, vect3D normal);

/**
 * @brief Generates contacts between one rectangle and one rigid body.
 *
 * @param a    rectangle to test against.
 * @param o    body to test.
 * @param v    the body's eight world-space corners, precomputed by the caller
 *             because it is reused across every rectangle in the cell.
 * @param port true if both portals are open, in which case contacts falling
 *             inside a portal outline are suppressed so bodies can pass through.
 * @return true if at least one contact was added.
 */
bool AAROBBContacts(AAR_struct* a, OBB_struct* o, vect3D* v, bool port);

#endif
